export const SELECT_CELL = 'SELECT_CELL';
export const SELECT_START = 'SELECT_START';
export const SELECT_UPDATE = 'SELECT_UPDATE';
export const SELECT_END = 'SELECT_END';
export const DRAG_ENTER = 'DRAG_ENTER';
export const SCROLL_TO_COLUMN = 'SCROLL_TO_COLUMN';
export const EDITOR_OPENED_AT_BOUNDARY = 'EDITOR_OPENED_AT_BOUNDARY';
export const EDITOR_CLOSED = 'EDITOR_CLOSED';

